spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zx88cvb/config-repo
          username: zx88cvb
          password: ****
          basedir: D:/Software_Development/Java_Development/WorkSpace/IntelliJ-IDEA-workspace/github/springcloud_sell/config/basedir

eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka